### ISSUE TITLE
:art: Recipe App | Ingredient Form | Mock-up

### ISSUE THREAD

**Issue by lukecookssw** [lukecookssw/Demo2#5]
[Relevant SugarLearning item](https://my.sugarlearning.com/SSW-FireBootCamp/items/14244/angular-building-a-recipe-app)

### Description
As a user, I want to see what my ingredient form will look like, so that I know what will be built.

### Tasks
- [ ] Mock-up Ingredient form
- [ ] Mock-up contains all ingredient data

### Acceptance Criteria
- [ ] Mock-up approved by Product Owner
