### ISSUE TITLE
:art: Recipe App | Recipe Form | Mock-up

### ISSUE THREAD

**Issue by lukecookssw** [lukecookssw/Demo2#7]
[Relevant SugarLearning item](https://my.sugarlearning.com/SSW-FireBootCamp/items/14244/angular-building-a-recipe-app)

### Description
As a Product Owner, I want a mock-up of my recipe form, so that I can see how users will add/edit recipes in the app.

### Tasks
- [ ] Mock up the Recipe form
- [ ] Capture all the recipe details (name, image, instructions, ingredients)
- [ ] Describe any functionality (button clicks etc.)

### Acceptance Criteria
- [ ] Mock-up approved by Product Owner
- [ ] Mock-up attached to the PBI
